---

  - name: install git
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - git

  - name: install lego-berry software - clone repository
    become: yes
    git: repro=https://github.com/andreasbehnke/lego-berry.git dest=/opt/lego-berry
