---

  - name: create symlink to motorhat service descriptor
    become: yes
    file: state=link src=/opt/lego-berry/python/robot/motorhat.service dest=/etc/systemd/system/motorhat.service

  - name: install motorhat service
    become: yes
    service: name=motorhat enabled=yes state=started
