---

  - name: install git
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - git

  - name: install mjpeg-streamer software - clone repository
    git: repo="https://github.com/jacksonliam/mjpg-streamer.git" dest="/home/pi/mjpg-streamer"
