---

  - name: install python software packages and git
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - python-dev
      - git

  - name: ensure path for adafruit software installation
    become: yes
    file: path="/opt/adafruit" state=directory mode=0755

  - name: clone adafruit repository
    become: yes
    git: repo="https://github.com/adafruit/Adafruit-Motor-HAT-Python-Library.git" dest="/opt/adafruit/Adafruit-Motor-HAT-Python-Library"

  - name: run setup for adafruit Library
    become: yes
    command: python setup.py install
    args:
      chdir: /opt/adafruit/Adafruit-Motor-HAT-Python-Library/
