---

  - name: install python software packages and git
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - python-dev
      - python-pip
      - git

  - name: install adafruit motorhat
    become: yes
    pip: name='git+https://github.com/adafruit/Adafruit-Motor-HAT-Python-Library'
